---
title: "K means Clustering in R"
output:
  word_document: default
  pdf_document: default
date: "2023-05-04"
---

In this R notebook, we will explore the use of k-means clustering as a technique for unsupervised learning. Specifically, we will apply k-means clustering to a dataset and examine the results of clustering using 3, 4, and 5 clusters.


```{r}
# import data set
buddymove_holidayiq = read.csv("~/Documents/Langara /Semester 3/DANA 4840 Classification II/Activities/Kmeans Clustering/buddymove_holidayiq.csv", stringsAsFactors=TRUE)
attach(buddymove_holidayiq)

# view data set
head(buddymove_holidayiq)

# remove first column
data = buddymove_holidayiq[1:30,-c(1)]
head(data)

#scale data 
data_scaled = scale(data)
head(data_scaled)

library(factoextra)
fviz_nbclust(data_scaled, kmeans, method = "wss") + geom_vline(xintercept = 3, linetype = 2)
```


K-means with 3 clusters

```{r}
####### 3 clusters #######

#clustering algorithm
km.res = kmeans(data, 3, nstart = 25)

#mean of each variable in each cluster
km.res$centers

#size in each cluster 
km.res$size


#mean using original data 
aggregate(buddymove_holidayiq[1:30,-c(1)], by=list(cluster=km.res$cluster), mean)

#graphing of clusters 
fviz_cluster(km.res, data = data,
             palette = c("#2E9FDF", "#00AFBB", "#E7B800", "#FC4E07"), 
             ellipse.type = "euclid", # Concentration ellipse
             star.plot = TRUE, # Add segments from centroids to items
             repel = TRUE, # Avoid label overplotting (slow)
             ggtheme = theme_minimal()
)
```


K-means with 4 clusters

```{r}
####### 4 clusters #######
#clustering algorithm
km.res4 = kmeans(data, 4, nstart = 25)

#mean of each variable in each cluster
km.res4$centers

#graphing of clusters 
fviz_cluster(km.res4, data = data,
             palette = c("#2E9FDF", "#00AFBB", "#E7B800", "#FC4E07"), 
             ellipse.type = "euclid", # Concentration ellipse
             star.plot = TRUE, # Add segments from centroids to items
             repel = TRUE, # Avoid label overplotting (slow)
             ggtheme = theme_minimal()
)
```


K-means with 5 clusters

```{r}
####### 5 clusters #######
#clustering algorithm
km.res5 = kmeans(data, 5, nstart = 25)

#mean of each variable in each cluster
km.res5$centers

#graphing of clusters 
fviz_cluster(km.res5, data = data,
             ellipse.type = "euclid", # Concentration ellipse
             star.plot = TRUE, # Add segments from centroids to items
             repel = TRUE, # Avoid label overplotting (slow)
             ggtheme = theme_minimal()
)
```

5 clusters seems to be appropriate

